# Generated by Django 2.2.1 on 2019-05-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_abs', models.CharField(max_length=50)),
                ('feature_path', models.CharField(max_length=200)),
                ('feature_is_R', models.CharField(max_length=1)),
                ('agd', models.CharField(help_text='average geodesic distance', max_length=200)),
                ('cf', models.CharField(help_text='conformal factors', max_length=200)),
                ('mytanhguassian', models.CharField(help_text='Gaussian curvature', max_length=200)),
                ('geobase', models.CharField(help_text='geodesic distance to bottom', max_length=200)),
                ('normalsangle', models.CharField(help_text='angle of normal vector', max_length=200)),
                ('sdfval', models.CharField(help_text='shape diameter function', max_length=200)),
                ('area', models.CharField(help_text='face area', max_length=200)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vertices', models.IntegerField(default=0)),
                ('total_faces', models.IntegerField(default=0)),
                ('total_area', models.FloatField(default=0)),
                ('min_area', models.FloatField(default=0)),
                ('max_area', models.FloatField(default=0)),
                ('average_area', models.FloatField(default=0)),
                ('stddev_area', models.FloatField(default=0)),
                ('variance_area', models.FloatField(default=0)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=10)),
                ('version', models.IntegerField(default=0)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Feature')),
                ('statistics', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Statistics')),
            ],
        ),
    ]
