# Generated by Django 2.2.1 on 2019-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190509_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesh',
            name='path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
