# Generated by Django 2.2.1 on 2019-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190513_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='dir',
            field=models.CharField(default='', max_length=200),
        ),
    ]
