# Generated by Django 2.2.1 on 2019-05-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190513_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='mytanhguassian',
            new_name='mytanhgaussian',
        ),
    ]
