# Generated by Django 2.2.1 on 2019-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190513_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=0)),
                ('dict', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scatter',
            constraint=models.UniqueConstraint(fields=('name', 'path', 'version'), name='unique_together'),
        ),
    ]
